- type: weightedRandomEntity
  id: BasicLootSecurityEntityTable
  weights:
    Flash: 1
    Handcuffs: 1
    Zipties: 1
    FlashlightSeclite: 1
    Tourniquet: 1

- type: weightedRandomEntity
  id: BasicLootSecurityRareEntityTable
  weights:
    ClothingEyesGlassesSunglasses: 1
    BoxHandcuff: 1

- type: weightedRandomEntity
  id: LootSecurityEntityTable
  weights:
    Flash: 1
    Handcuffs: 1
    Zipties: 1
    FlashlightSeclite: 1
    GrenadeFlashBang: 1
    SecurityWhistle: 1
    Tourniquet: 1

- type: weightedRandomEntity
  id: LootSecurityRareEntityTable
  weights:
    ClothingEyesGlassesSunglasses: 1
    BoxHandcuff: 1
    BoxFlashbang: 1
    TearGasGrenade: 1
    WeaponDisabler: 1
    Stunbaton: 1

- type: weightedRandomEntity
  id: LootArmoryEntityTable
  weights:
    RiotShield: 1
    RiotBulletShield: 1
    RiotLaserShield: 1
    ClothingHeadHelmetBasic: 1
    ClothingHeadHelmetRiot: 1
    ClothingOuterArmorBasic: 1
    ClothingOuterArmorRiot: 1
    ClothingOuterArmorBulletproof: 1
    WeaponDisabler: 1
    WeaponPistolMk58: 1
    WeaponRifleLecter: 1
    WeaponSubMachineGunDrozd: 1
    WeaponLaserCarbine: 1
    WeaponShotgunKammerer: 1

- type: weightedRandomEntity
  id: LootArmoryRareEntityTable
  weights:
    ClothingHeadHelmetSwat: 1
    WeaponShotgunEnforcer: 1

- type: weightedRandomEntity
  id: LootArmoryGunsEntityTable
  weights:
    WeaponDisabler: 1
    WeaponPistolMk58: 1
    WeaponRifleLecter: 1
    WeaponSubMachineGunDrozd: 1
    WeaponLaserCarbine: 1
    WeaponShotgunKammerer: 1

- type: weightedRandomEntity
  id: LootArmoryGunsRareEntityTable
  weights:
    WeaponShotgunEnforcer: 1

- type: weightedRandomEntity
  id: LootArmoryArmorEntityTable
  weights:
    RiotShield: 1
    RiotBulletShield: 1
    RiotLaserShield: 1
    ClothingHeadHelmetBasic: 1
    ClothingHeadHelmetRiot: 1
    ClothingOuterArmorBasic: 1
    ClothingOuterArmorRiot: 1
    ClothingOuterArmorBulletproof: 1

- type: weightedRandomEntity
  id: LootArmoryArmorRareEntityTable
  weights:
    ClothingHeadHelmetSwat: 1
