# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  category: Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  id: BaseAmmoRecipe
  category: Ammo
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseAmmoRecipe
  id: BaseEmptyAmmoRecipe
  completetime: 1

# Recipes

- type: latheRecipe
  id: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Stunbaton

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Truncheon

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ClothingBackpackElectropack
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShellTranquilizer
  materials:
    Plastic: 240
    Steel: 160
    Glass: 80
    Plasma: 160
    Silver: 80

- type: latheRecipe
  id: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  parent: TargetHuman
  id: TargetClown

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol
  materials:
    Steel: 145

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolPractice
  materials:
    Steel: 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolUranium
  materials:
    Steel: 25
    Plastic: 65
    Uranium: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolIncendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGun
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMounted
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistol
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnum
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle
  materials:
    Steel: 475


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRiflePractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleUranium
  materials:
    Steel: 25
    Plastic: 300
    Uranium: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLightRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifle
  materials:
    Steel: 565

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRiflePractice
  materials:
    Steel: 205


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleUranium
  materials:
    Steel: 25
    Plastic: 360
    Uranium: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleIncendiary
  materials:
    Steel: 25
    Plastic: 540

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifle
  materials:
    Steel: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifle
  materials:
    Steel: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxLethalshot
  materials:
    Steel: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxBeanbag
  materials:
    Steel: 160
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunSlug
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: SpeedLoaderMagnumEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnum
  materials:
    Steel: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumPractice
  materials:
    Steel: 90

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumUranium
  materials:
    Steel: 50
    Plastic: 150
    Uranium: 110

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumIncendiary
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineShotgunEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgun
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunBeanbag
  materials:
    Steel: 150
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunSlug
  materials:
    Steel: 190
    Plastic: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunIncendiary
  materials:
    Steel: 100
    Plastic: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolIncendiary
  materials:
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumIncendiary
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleIncendiary
  materials:
    Plastic: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleIncendiary
  materials:
    Plastic: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunFlare
  materials:
    Steel: 80
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunIncendiary
  materials:
    Steel: 80
    Plastic: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolPractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumPractice
  materials:
    Steel: 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRiflePractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRiflePractice
  materials:
    Steel: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunPractice
  materials:
    Steel: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolUranium
  materials:
    Plastic: 300
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumUranium
  materials:
    Plastic: 240
    Uranium: 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleUranium
  materials:
    Plastic: 600
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleUranium
  materials:
    Plastic: 500
    Uranium: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunUranium
  materials:
    Plastic: 320
    Uranium: 240

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  completetime: 6
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: WeaponDisabler
  id: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: MagazineGrenadeEmpty
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: GrenadeEMP
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: GrenadeBlast
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: GrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: PortableRecharger
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500
