- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcommOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcomm
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcommPDA
    ears: ClothingHeadsetAltCentComm
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcomm
